app/models.py
"""Database models."""
from . import db


class Author(db.Model):
    """Author model."""

    author_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    books = db.relationship("Book", backref="author")

    def __repr__(self):
        """Return the object representation."""
        return "<Author: {}>".format(self.books)


class Book(db.Model):
    """Book model."""

    book_id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.Integer, db.ForeignKey("author.author_id"))
    title = db.Column(db.String)

app/__init__.py
"""Constructor of the main app."""
import logging

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_pagedown import PageDown
from flask_sqlalchemy import SQLAlchemy

from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
pagedown = PageDown()


def create_app(config_name):
    """Start Flask application."""
    app = Flask(__name__)

    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    pagedown.init_app(app)

    # setting logging ...
    app.logger.setLevel(app.config["LOGGER_LEVEL"])
    handler = logging.FileHandler("logs/flaskpine.log")
    app.logger.addHandler(handler)

    # if app.config["SSL_REDIRECT"]:
    #     from flask_sslify import SSLify
    #     sslify = SSLify(app)

    from .main import main as main_blueprint

    app.register_blueprint(main_blueprint)

    # from .auth import auth as auth_blueprint
    # app.register_blueprint(auth_blueprint, url_prefix='/auth')

    # from .api import api as api_blueprint
    # app.register_blueprint(api_blueprint, url_prefix='/api/v1')

    return app

app/main/__init__.py
"""Main blueprint."""
from flask import Blueprint


def do_import():
    """Trick to bypass git_commit error of being imported by unused."""
    from . import views

    views.logger


main = Blueprint("main", __name__)
do_import()

app/main/views.py
"""Views from main."""

from flask import render_template, request

from app import db
from app import logging as logger
from app.models import Author, Book

from . import main


def get_books():
    """Return the books."""
    return (
        db.session.query(Book, Author).filter(Book.author_id == Author.author_id).all()
    )


@main.route("/", methods=["GET"])
def home():
    """Start get endpoint."""
    return render_template("index.html", books=get_books())


@main.route("/submit", methods=["POST"])
def submit():
    """Submission of a book."""
    title = request.form["title"]
    author_name = request.form["author"]

    author = db.session.query(Author).filter(Author.name == author_name).first()
    logger.debug(author)

    # check if author already exists in db
    if author:
        author_id = author.author_id
        book = Book.query.filter_by(author_id=author_id).first()
        book.title = title
        db.session.commit()
    else:
        author = Author(name=author_name)
        db.session.add(author)
        db.session.commit()

        book = Book(author_id=author.author_id, title=title)
        db.session.add(book)
        db.session.commit()
    return render_template("index.html", books=get_books())


@main.route("/delete/<int:id>", methods=["DELETE"])
def delete_book(id):
    """Delete book by the passed id."""
    book = Book.query.get(id)
    author = Author.query.filter_by(author_id=book.author_id).first()
    if author:
        db.session.delete(author)
    db.session.delete(book)
    db.session.commit()

    return render_template("index.html", books=get_books())


@main.route("/get-edit-form/<int:id>", methods=["GET"])
def get_edit_form(id):
    """Edit a book by passed id."""
    book = Book.query.get(id)
    author = Author.query.get(book.author_id)

    return render_template("edit.html", book=book, author=author, id=id)


@main.route("/update/<int:id>", methods=["PUT"])
def update_book(id):
    """Upate book by id."""
    db.session.query(Book).filter(Book.book_id == id).update(
        {"title": request.form["title"]}
    )
    db.session.commit()

    return render_template("_table-body.html", books=get_books())

app/templates/_table-body.html
<tbody id="new-book" x-init>
    {%for book in books%}
    <tr id="{{book.Book.book_id}}">
        <td>{{book.Book.title}}</td>
        <td>{{book.Author.name}}</td>
        <td>
            <a class="btn btn-primary" href="/get-edit-form/{{book.Book.book_id}}" x-target="{{book.Book.book_id}}">Edit Title</a>
        </td>
        <td>
            <form x-target="new-book" method="delete" action="/delete/{{book.Book.book_id}}">
                <button class="btn btn-primary">Delete</button>
            </form>
        </td>
    </tr>
    {%endfor%}
</tbody>

app/templates/edit.html
<tr id="{{book.book_id}}" x-data="{ title: '{{book.title}}' }">
    <td><input name="title" value="{{book.title}}" x-model="title"/></td>
    <td>{{author.name}}</td>
    <td>
        <a class="btn btn-primary" href="{{url_for('main.home')}}" x-target="{{book.book_id}}">Cancel</a>
    </td>
    <td>
        <form x-init x-target="new-book" method="put" action="/update/{{id}}">
            <input type="hidden" id="title" name="title" x-model="title">
            <button class="btn btn-primary">Save</button>
        </form>
    </td>
</tr>

<div aria-live="polite">
    <ul x-sync id="notifications">Editing ...</ul>
</div>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Flask ALPINE AJAX App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- AlpineJS Ajax -->
    <script defer src="https://cdn.jsdelivr.net/npm/@imacrayon/alpine-ajax@0.7.0/dist/cdn.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.11.1/dist/cdn.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">

</head>

<body>
    <h1>Book Recommendations</h1>
    <form id="form_data" x-init x-target="new-book form_data" method="post" class="mb-3" action="/submit">
        <input type="text" placeholder="Book Title" name="title" class="form-control mb-3" />
        <input type="text" placeholder="Book Author" name="author" class="form-control mb-3" />
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <table class="table">
        <thead>
          <tr>
            <th scope="col">Book Title</th>
            <th scope="col">Book Author</th>
          </tr>
        </thead>
            {% include '_table-body.html' %}
    </table>

    <div aria-live="polite">
        <ul x-sync id="notifications"></ul>
    </div>
</body>


</html>

app/templates/table-body.html
<tbody id="new-book" x-init>
    {%for book in books%}
    <tr id="{{book.Book.book_id}}">
        <td>{{book.Book.title}}</td>
        <td>{{book.Author.name}}</td>
        <td>
            <a class="btn btn-primary" href="/get-edit-form/{{book.Book.book_id}}" x-target="{{book.Book.book_id}}">Edit Title</a>
        </td>
        <td>
            <form x-target="new-book" method="delete" action="/delete/{{book.Book.book_id}}">
                <button class="btn btn-primary">Delete</button>
            </form>
        </td>
    </tr>
    {%endfor%}
</tbody>